spring:
  application:
    name: restaurant-microservice
#  datasource:
#    url: jdbc:postgresql://localhost:5432/restaurant_database
#    username: postgres
#    password: admin123
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8083
