spring:
  application:
    name: restaurant-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_database
    username: postgres
    password: admin123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8083
